# mysql
mysql:
  username: root
  password: "123456"
  ipaddress: localhost
  port: 3306
  dbname: douyin

# redis
redis:
  ipaddress: localhost
  port: 6379
  authpassword: 123456
  maxidle: 5              #连接池最大空闲数
  maxactive: 0            #连接池最大连接数 0 表示不设上
  db: 1

# resource(静态图片和视频的资源)
resouece:
  ipaddress: localhost
  port: 8000